[package]
name = "game-macroquad-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
macroquad = "0.4.13"
renet = "1.0.0"
renet_netcode = "1.0.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }

[profile.dev.package.'*']
opt-level = 3
