[package]
name = "game-macroquad-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
macroquad = "0.4.13"
tiled = "0.13.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }

[profile.dev.package.'*']
opt-level = 3
