# https://rust-lang.github.io/rustfmt/

edition = "2024"

max_width = 100                 # default: true
use_field_init_shorthand = true # default: true 
hard_tabs = false               # default: false
tab_spaces = 3                  # default: 4

# Unstable features
format_strings = true          # default: false
imports_granularity = "Crate"  # default: "Preserve"
group_imports = "One"          # default: "Preserve"
wrap_comments = true           # default: false
fn_single_line = false         # default: false
comment_width = 90             # default: 80
empty_item_single_line = false # default: true
